baseURL = "adnan-najjar.github.io"
languageCode = "en-us"
title = "Adnan Najjar"
theme = "hugo-profile"
Paginate = 3
enableRobotsTXT = false

[outputs]
home = [ "HTML", "RSS", "JSON" ]
page = [ "HTML", "RSS" ]

[markup.goldmark.renderer]
unsafe = true

[[Menus.main]]
identifier = "Blog"
name = "Blogs"
title = "Blog Posts"
url = "/blogs"
weight = 1

[params]
title = "Adnan Najjar"
favicon = "/fav.png"
useBootstrapCDN = false
mathjax = false
animate = true

  [params.font]
  fontSize = "1rem"
  fontWeight = 400
  lineHeight = 1.5
  textAlign = "left"

  [params.navbar]
  align = "ms-auto"
  brandName = "Adnan Najjar"
  disableSearch = true
  enableSeparator = true

    [params.navbar.stickyNavBar]
    enable = true
    showOnScrollUp = true

    [params.navbar.menus]
    disableAbout = false
    disableExperience = false
    disableEducation = false
    disableProjects = false
    disableCertifications = false
    disableContact = true

  [params.hero]
  enable = true
  backgroundImage = "https://www.ncsc.gov.uk/images/Annual-Review-2022-Threats-Risks-Vulnerabilities-image.jpg"
  intro = "Hi, my name is"
  title = "Adnan."
  subtitle = "I break things to fix them."

    [params.hero.button]
    enable = false
    name = "Resume"
    url = "#"
    download = true
    newPage = false

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-github"
url = "https://github.com/Adnan-Najjar"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-linkedin"
url = "https://www.linkedin.com/in/adnan-najjar-9b302a306"

# [[params.hero.socialLinks.customIcons]]
# icon = "/fav.png"
# url = "https://example.com"

  [params.about]
  enable = true
  title = "About Me"
  image = "https://media.licdn.com/dms/image/v2/D4D03AQEmKJXbFU2jfw/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1718312829317?e=1740614400&v=beta&t=5Vxdoctb8iTGCG7zSOcOeo1lrKOM-rwMsFEPvhop-QU"
  content = """
Hi, I’m Adnan, and I’m passionate about protecting privacy in our digital world. I’m currently on the lookout for a cybersecurity analyst position where I can make a difference. I love tackling complex problems and working with technology, using my programming skills to create practical solutions.

I’m good at managing my time, which helps me prioritize tasks and stay organized. My programming background allows me to build tools and scripts that enhance efficiency in cybersecurity efforts. I also enjoy problem-solving, which helps me navigate challenges effectively.

I believe in the importance of following laws and regulations to keep organizations compliant with industry standards. Continuous learning is a priority for me, as I want to stay updated on the latest threats and technologies.

What excites me most about cybersecurity is the blend of problem-solving and the opportunity to help people protect their privacy. I’m eager to connect with cybersecurity recruiters and hiring managers at technology firms and government agencies, and I look forward to contributing to their security goals.
"""

    [params.about.skills]
    enable = true
    title = "Here are a some technologies I've been working with recently:"
    items = [ "Python", "Java", "C", "Go", "bash" ]

  [params.experience]
  enable = false

    [[params.experience.items]]
    job = "Lorem Ipsum"
    company = "Lorem"
    companyUrl = "https://example.com"
    date = "Sep 2025 - Dec 2026"
    content = """
Lorem ipsum dolor sit amet consectetur adipisicing elit. [example org.](https://example.com) Lorem ipsum dolor sit amet consectetur adipisicing elit.

- Lorem ipsum dolor sit amet consectetur adipisicing elit.
- Lorem ipsum dolor sit amet consectetur adipisicing elit.
"""

      [params.experience.items.featuredLink]
      enable = true
      url = "https://example.com"

      [params.experience.items.info]
      enable = true
      content = "Lorem ipsum dolor sit amet consectetur adipisicing elit."

  [params.education]
  enable = true
  index = true

    [[params.education.items]]
    title = "Bachelor of Science in Cyber Security"
    date = "2022 - 2026"
    GPA = "3.65 out of 4.0"
    content = """"""

      [params.education.items.school]
      name = "Canadian University Dubai"
      url = "https://cud.ac.ae"

      [params.education.items.featuredLink]
      enable = true
      name = "My academic record"
      url = "https://example.com"

  [params.certifications]
  enable = true

    [[params.certifications.items]]
    title = "Google Cybersecurity Certificate"
    # content = ""
    url = "https://example.com"
    # image = "/images/achievment.jpg"

  [params.projects]
  enable = true

    [[params.projects.items]]
    title = "Hugo site"
    content = "This site :)"
    image = "https://www.datocms-assets.com/205/1516783640-hugo.svg?fit=max&fm=jpg&w=1000"
    badges = [ "Hugo" ]

      [params.projects.items.featured]
      name = "Demo"
      link = "https://adnan-najjar.github.io"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/adnan-najjar/adnan-najjar.github.io"

    [[params.projects.items]]
    title = "Organize PDF"
    content = "A simple script to organize pdfs in multiple folders based on their content, utilizing multi-threading of parallel command."
    badges = [ "Bash" ]

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/adnan-najjar/organize_pdfs"

  [params.contact]
  enable = false

[params.footer.recentPosts]
path = "blogs"
count = 3
title = "Recent Posts"
enable = true
disableFeaturedImage = false

[params.footer.socialNetworks]
github = "https://github.com/Adnan-Najjar"
linkedin = "https://www.linkedin.com/in/adnan-najjar-9b302a306"
email = "adnan.najjar@gmail.com"

  [params.listPages]
  disableFeaturedImage = false

  [params.singlePages]
  socialShare = true

    [params.singlePages.readTime]
    enable = true
    content = "min read"

    [params.singlePages.scrollprogress]
    enable = true

    [params.singlePages.tags]
    openInNewTab = true

  [params.terms]
  read = "Read"
  toc = "Table Of Contents"
  pageNotFound = "Page Not Found :("
  emailText = "Check out this site"

  [params.datesFormat]
  article = "Jan 2, 2006"
  articleList = "Jan 2, 2006"
  articleRecent = "Jan 2, 2006"
