baseURL = "adnan-najjar.github.io"
languageCode = "en-us"
title = "Adnan Najjar"
theme = "hugo-profile"
Paginate = 3
enableRobotsTXT = false

[outputs]
home = [ "HTML", "RSS", "JSON" ]
page = [ "HTML", "RSS" ]

[markup.goldmark.renderer]
unsafe = true

[[Menus.main]]
identifier = "Blog"
name = "Blogs"
title = "Blog Posts"
url = "/blogs"
weight = 1

[params]
title = "Adnan Najjar"
favicon = "/fav.png"
useBootstrapCDN = false
mathjax = false
animate = true

  [params.font]
  fontSize = "1rem"
  fontWeight = 400
  lineHeight = 1.5
  textAlign = "left"

  [params.navbar]
  align = "ms-auto"
  brandName = "Adnan Najjar"
  disableSearch = true
  enableSeparator = true

    [params.navbar.stickyNavBar]
    enable = true
    showOnScrollUp = true

    [params.navbar.menus]
    disableAbout = false
    disableExperience = false
    disableEducation = false
    disableProjects = false
    disableCertifications = false
    disableContact = true

  [params.hero]
  enable = true
  backgroundImage = "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1744&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
  intro = "Hi, my name is"
  title = "Adnan."
  # subtitle = "I break things to fix them."

    [params.hero.button]
    enable = false
    name = "Resume"
    url = "#"
    download = true
    newPage = false

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-github"
url = "https://github.com/Adnan-Najjar"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-linkedin"
url = "https://www.linkedin.com/in/adnan-najjar-9b302a306"

# [[params.hero.socialLinks.customIcons]]
# icon = "/fav.png"
# url = "https://example.com"

  [params.about]
  enable = true
  title = "About Me"
  image = "https://media.licdn.com/dms/image/v2/D4D03AQEQ7rZmS7HzZA/profile-displayphoto-shrink_800_800/B4DZVJCsP_GcAc-/0/1740687197957?e=1753920000&v=beta&t=YLBe1agMtHeMqoYuJjy916tefsBm8l6-0mn2pG1bF7A"
  content = """
I am a cybersecurity student who is excited about learning how to protect information from digital threats. I enjoy exploring malware and understanding how to keep systems safe. 

I am eager to learn more about threat detection and security measures. I look forward to connecting with others in the cybersecurity field and sharing ideas!
"""

    [params.about.skills]
    enable = true
    title = "Here are a some technologies I've been working with recently:"
    items = [ "Python", "Java", "Go", "bash" ]

  [params.experience]
  enable = false

    [[params.experience.items]]
    job = "Lorem Ipsum"
    company = "Lorem"
    companyUrl = "https://example.com"
    date = "Sep 2025 - Dec 2026"
    content = """
Lorem ipsum dolor sit amet consectetur adipisicing elit. [example org.](https://example.com) Lorem ipsum dolor sit amet consectetur adipisicing elit.

- Lorem ipsum dolor sit amet consectetur adipisicing elit.
- Lorem ipsum dolor sit amet consectetur adipisicing elit.
"""

      [params.experience.items.featuredLink]
      enable = true
      url = "https://example.com"

      [params.experience.items.info]
      enable = true
      content = "Lorem ipsum dolor sit amet consectetur adipisicing elit."

  [params.education]
  enable = true
  index = true

    [[params.education.items]]
    title = "Google Cybersecurity Certificate"
    date = "Nov 2024 - Jan 2025"

      [params.education.items.school]
      name = "Coursera"
      url = "https://coursera.org"

      [params.education.items.featuredLink]
      enable = true
      name = "My certificate"
      url = "https://coursera.org/share/0120e9a3edb06c2712a5637512111fe9"

    [[params.education.items]]
    title = "Nomu Al Ghurair - Cybersecurity"
    date = "Nov 2024 - Jan 2025"

      [params.education.items.school]
      name = "Spritns"
      url = "https://sprints.ai"

      [params.education.items.featuredLink]
      enable = true
      name = "My certificate"
      url = "https://sprints.ai/en/journeys/learning/ID%20-%20SPR%20-%20NL6Q29/view-certificate-serial"

    [[params.education.items]]
    title = "Bachelor of Science in Cyber Security"
    date = "Aug 2022 - In Progress"
    GPA = "3.65 out of 4.0"
    content = """"""

      [params.education.items.school]
      name = "Canadian University Dubai"
      url = "https://cud.ac.ae"

      [params.education.items.featuredLink]
      enable = true
      name = "My academic record"
      url = "https://cud.ac.ae"

  [params.certifications]
  enable = false

    [[params.certifications.items]]
    title = ""
    url = ""
    image = ""

  [params.projects]
  enable = true

    [[params.projects.items]]
    title = "Organize PDF"
    content = "A simple script to organize pdfs in multiple folders based on their content, utilizing multi-threading of parallel command."
    image = ""
    badges = [ "Bash" ]

      # [params.projects.items.featured]
      # name = "Demo"
      # link = "https://adnan-najjar.github.io"

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/adnan-najjar/organize_pdfs"

    [[params.projects.items]]
    title = "Ansible Personal Config"
    content = "An ansible playbook to configure and setup my fedora linux machine"
    image = "https://upload.wikimedia.org/wikipedia/commons/2/24/Ansible_logo.svg"
    badges = [ "ansible" ]

      [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/adnan-najjar/ansible_personal_config"

  [params.contact]
  enable = false

[params.footer.recentPosts]
path = "blogs"
count = 3
title = "Recent Posts"
enable = true
disableFeaturedImage = false

[params.footer.socialNetworks]
github = "https://github.com/Adnan-Najjar"
linkedin = "https://www.linkedin.com/in/adnan-najjar-9b302a306"
email = "adnan.najjar@gmail.com"

  [params.listPages]
  disableFeaturedImage = false

  [params.singlePages]
  socialShare = true

    [params.singlePages.readTime]
    enable = true
    content = "min read"

    [params.singlePages.scrollprogress]
    enable = true

    [params.singlePages.tags]
    openInNewTab = true

  [params.terms]
  read = "Read"
  toc = "Table Of Contents"
  pageNotFound = "Page Not Found :("
  emailText = "Check out this site"

  [params.datesFormat]
  article = "Jan 2, 2006"
  articleList = "Jan 2, 2006"
  articleRecent = "Jan 2, 2006"
